package entity.loans;

import java.util.ArrayList;

public class Contracts {
    public String contractId;
    public String customerId;
    public String organizationId;
    public String organizationName;
    public String brandName;
    public String companyCnpj;
    public String ipocCode;
    public String productName;
    public String productType;
    public String productSubType;
    public String contractDate;
    public String settlementDate;
    public double contractAmount;
    public String currency;
    public String dueDate;
    public String instalmentPeriodicity;
    public String instalmentPeriodicityAdditionalInfo;
    public String firstInstalmentDueDate;
    public double cET;
    public String amortizationScheduled;
    public String amortizationScheduledAdditionalInfo;
    public String cnpjConsignee;
    public ArrayList<InterestRate> interestRates;
    public ArrayList<ContractedFee> contractedFees;
    public ArrayList<ContractedFinanceCharge> contractedFinanceCharges;
    public String contractId;
    public String customerId;
    public String organizationId;
    public String organizationName;
    public String currency;
    public String warrantyType;
    public String warrantySubType;
    public double warrantyAmount;
    public String contractId;
    public String customerId;
    public String organizationId;
    public String organizationName;
    public String typeNumberOfInstalments;
    public int totalNumberOfInstalments;
    public String typeContractRemaining;
    public int contractRemainingNumber;
    public int paidInstalments;
    public int dueInstalments;
    public int pastDueInstalments;
    public Object balloonPayments;
    public String contractId;
    public String customerId;
    public String organizationId;
    public String organizationName;
    public int paidInstalments;
    public double contractOutstandingBalance;
    public ArrayList<Release> releases;
}
